import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

describe('3dvr world prototype route', () => {
  it('ships a full-screen 3d homepage world with device-safe messaging', async () => {
    const html = await readFile(new URL('../3dvr-world/index.html', import.meta.url), 'utf8');

    assert.match(html, /3DVR 3D Homepage World/);
    assert.match(html, /Step into the 3DVR world\./);
    assert.match(html, /frame-lab--fullscreen/);
    assert.match(html, /Open Portal/);
    assert.match(html, /Portal HUD glow/);
    assert.match(html, /Three\.js world/);
    assert.match(html, /Castle game layer/);
    assert.match(html, /A full-screen 3DVR homepage world with touch, tilt, and direct paths into plans/);
    assert.match(html, /Power stars/);
    assert.match(html, /id="worldStars"/);
    assert.match(html, /Warp Room/);
    assert.match(html, /data-secret-star/);
    assert.match(html, /data-warp-zone="secret"/);
    assert.match(html, /scene-castle__keep/);
    assert.match(html, /CASTLE/);
    assert.match(html, /scene-castle/);
    assert.match(html, /scene-coin-trail/);
    assert.match(html, /id="worldCanvasFallback"/);
    assert.match(html, /class="world-canvas-fallback"/);
    assert.match(html, /id="worldThreeCanvas"/);
    assert.match(html, /class="world-three-canvas"/);
    assert.match(html, /Stage \+ panels/);
    assert.match(html, /id="zoneMetrics"/);
    assert.match(html, /id="zoneDepthFill"/);
    assert.match(html, /scene-radar/);
    assert.match(html, /scene-core/);
    assert.match(html, /telemetry-panel/);
    assert.match(html, /world-topbar/);
    assert.match(html, /class="hero-points"/);
    assert.match(html, /class="world-content"/);
    assert.match(html, /class="hero-copy world-intro"/);
    assert.match(html, /class="world-sidebar"/);
    assert.match(html, /id="worldMotion"/);
    assert.match(html, /id="motionToggle"/);
    assert.match(html, /id="motionState"/);
    assert.match(html, /zone-detail__secret/);
    assert.match(html, /zone-detail__secret-link/);
    assert.match(html, /zone-detail__secret-portal/);
    assert.match(html, /data-secret-portal/);
    assert.match(html, /href="\/pages\/portfolio\.html#projects"/);
    assert.match(html, /scene-secret-callout/);
    assert.match(html, /class="world-mobile-hint"/);
    assert.doesNotMatch(html, /class="world-camera"/);
    assert.doesNotMatch(html, /id="cameraModeToggle"/);
    assert.doesNotMatch(html, /id="cameraState"/);
    assert.doesNotMatch(html, /id="statusPill"/);
    assert.doesNotMatch(html, /class="world-controls"/);
    assert.doesNotMatch(html, /data-zone-button=/);
    assert.match(html, /data-zone="arrival"/);
    assert.match(html, /data-zone="arena"/);
    assert.match(html, /data-zone="studio"/);
    assert.match(html, /data-zone="rooftop"/);
    assert.match(html, /href="styles\.css"/);
    assert.match(html, /src="script\.js"/);
    assert.doesNotMatch(html, /fonts\.googleapis/i);
    assert.doesNotMatch(html, /fonts\.gstatic/i);
    assert.doesNotMatch(html, /KODE/i);
    assert.doesNotMatch(html, /sports-club/i);
  });

  it('uses a Three.js world layer with css perspective and scripted zone switching', async () => {
    const css = await readFile(new URL('../3dvr-world/styles.css', import.meta.url), 'utf8');
    const js = await readFile(new URL('../3dvr-world/script.js', import.meta.url), 'utf8');

    assert.match(css, /perspective:\s*1800px/);
    assert.match(css, /\.club-frame/);
    assert.match(css, /\.club-frame::before/);
    assert.match(css, /transform-style:\s*preserve-3d/);
    assert.match(css, /\.frame-lab--fullscreen/);
    assert.match(css, /\.world-topbar/);
    assert.match(css, /\.world-body\.world-ready/);
    assert.match(css, /\.frame-hud__panel/);
    assert.match(css, /\.zone-detail__meter-fill/);
    assert.match(css, /\.scene-radar/);
    assert.match(css, /\.scene-core/);
    assert.match(css, /\.scene-core__label/);
    assert.match(css, /\.club-frame\[data-zone="arena"\] \.scene-core/);
    assert.match(css, /\.club-frame\[data-zone="studio"\] \.scene-core/);
    assert.match(css, /\.world-stars/);
    assert.match(css, /\.warp-room/);
    assert.match(css, /\.warp-room__door/);
    assert.match(css, /\.scene-secret-star/);
    assert.match(css, /\.scene-secret-callout/);
    assert.match(css, /\.scene-castle/);
    assert.match(css, /\.scene-coin-trail/);
    assert.match(css, /\.world-canvas-fallback/);
    assert.match(css, /\.club-frame\.world-canvas-active \.world-canvas-fallback/);
    assert.match(css, /\.world-three-canvas/);
    assert.match(css, /\.club-frame\.world-three-active \.world-three-canvas/);
    assert.match(css, /\.club-frame\.world-three-active \.scene-castle/);
    assert.doesNotMatch(css, /\.world-camera/);
    assert.match(css, /\.club-frame\.is-warping/);
    assert.match(css, /\.club-frame\.is-snapping/);
    assert.match(css, /\.club-frame\.is-warping::before/);
    assert.match(css, /\.club-frame\.is-warping::after/);
    assert.match(css, /\.club-frame\.is-warping \.scene--back/);
    assert.match(css, /\.club-frame\.is-warping \.scene-core/);
    assert.match(css, /\.zone-detail\.is-secret/);
    assert.match(css, /\.club-frame\[data-camera="wide"\] \.scene-core/);
    assert.match(css, /\.club-frame\[data-camera="close"\] \.scene-card/);
    assert.match(css, /\.club-frame\[data-camera="high"\] \.scene-core/);
    assert.match(css, /@keyframes core-breathe/);
    assert.match(css, /@keyframes coin-float/);
    assert.match(css, /@keyframes flag-wave/);
    assert.match(css, /@keyframes warp-flash/);
    assert.match(css, /@keyframes camera-snap/);
    assert.match(css, /@keyframes zone-wash/);
    assert.match(css, /@keyframes room-wipe/);
    assert.match(css, /\.scene--back/);
    assert.match(css, /translate3d\(calc\(var\(--float-x\) \* -0\.24\)/);
    assert.match(css, /--scene-lift/);
    assert.match(css, /\.hero-points/);
    assert.match(css, /\.world-content/);
    assert.match(css, /\.world-intro/);
    assert.match(css, /\.world-sidebar/);
    assert.match(css, /\.world-motion/);
    assert.match(css, /\.world-motion__button/);
    assert.match(css, /\.world-mobile-hint/);
    assert.match(css, /\.world-mobile-hint\[hidden\]/);
    assert.match(css, /\.zone-detail__secret-portal\[hidden\]/);
    assert.match(css, /\.club-frame\[data-zone="secret"\] \.world-mobile-hint/);
    assert.match(css, /@font-face/);
    assert.match(css, /chakra-petch-400-latin\.woff2/);
    assert.match(css, /instrument-serif-400-latin\.woff2/);
    assert.match(css, /text-size-adjust:\s*100%/);
    assert.match(css, /touch-action:\s*pan-y/);
    assert.match(js, /const zones = \{/);
    assert.match(js, /zoneMetrics/);
    assert.match(js, /worldStars/);
    assert.match(js, /sceneCoreLabel/);
    assert.match(js, /sceneMarquee/);
    assert.match(js, /sceneStatusLeft/);
    assert.match(js, /sceneStatusRight/);
    assert.match(js, /secretStar/);
    assert.match(js, /warpButtons/);
    assert.match(js, /zoneDepthFill/);
    assert.match(js, /metrics:/);
    assert.match(js, /depth:/);
    assert.match(js, /renderZone\(activeZone\)/);
    assert.match(js, /pointermove/);
    assert.match(js, /DeviceOrientationEvent/);
    assert.match(js, /deviceorientation/);
    assert.match(js, /requestPermission/);
    assert.match(js, /handleMotionToggle/);
    assert.match(js, /touchstart/);
    assert.match(js, /touchmove/);
    assert.match(js, /stepZone/);
    assert.match(js, /motionPermissionRequired/);
    assert.match(js, /requestAnimationFrame/);
    assert.match(js, /targetTiltX/);
    assert.match(js, /ambientEnabled/);
    assert.match(js, /updateAmbientMotion/);
    assert.match(js, /collectSecretStar/);
    assert.match(js, /secretWarpButton/);
    assert.match(js, /secretPortalButton/);
    assert.match(js, /secretCallout/);
    assert.match(js, /worldMobileHint/);
    assert.match(js, /worldCanvasFallback/);
    assert.match(js, /worldThreeCanvas/);
    assert.match(js, /createCanvasFallbackWorld/);
    assert.match(js, /CanvasRenderingContext2D|drawCastle|drawPortal/);
    assert.match(js, /world-canvas-active/);
    assert.match(js, /THREE_CDN_URL/);
    assert.match(js, /cdnjs\.cloudflare\.com\/ajax\/libs\/three\.js\/r128\/three\.min\.js/);
    assert.match(js, /createThreeWorld/);
    assert.match(js, /WebGLRenderer/);
    assert.match(js, /PerspectiveCamera/);
    assert.match(js, /TorusGeometry/);
    assert.match(js, /ExtrudeGeometry/);
    assert.match(js, /world-three-active/);
    assert.match(js, /world-three-unavailable/);
    assert.match(js, /zoneDetail\.classList\.toggle\('is-secret', zoneKey === 'secret'\)/);
    assert.match(js, /snapTransitionTimer/);
    assert.doesNotMatch(js, /cameraModeToggle/);
    assert.doesNotMatch(js, /cameraState/);
    assert.doesNotMatch(js, /setCameraMode/);
    assert.match(js, /warpTransitionTimer/);
    assert.match(js, /lift: '0px'/);
    assert.match(js, /lift: '-12px'/);
    assert.match(js, /lift: '9px'/);
    assert.match(js, /lift: '-16px'/);
    assert.match(js, /lift: '-4px'/);
    assert.match(js, /--scene-lift/);
    assert.match(js, /Castle attic/);
    assert.match(js, /statusLeft/);
    assert.match(js, /statusRight/);
    assert.match(js, /pages\/portfolio\.html#projects/);
    assert.match(js, /Warping to the projects room\./);
    assert.match(js, /secretPortalButton\.href/);
    assert.match(js, /renderZone\('secret'\)/);
    assert.match(js, /frame\.classList\.add\('is-landing', 'is-warping', 'is-snapping'\)/);
    assert.match(js, /zone-detail__secret-link/);
    assert.match(js, /zone-detail__secret-portal/);
    assert.match(js, /Entering \$\{zone\.room\}\./);
    assert.match(css, /\.club-frame::after/);
    assert.doesNotMatch(js, /world-locked/);
  });

  it('keeps the legacy frame-club-test route as a redirect to the canonical world route', async () => {
    const html = await readFile(new URL('../frame-club-test/index.html', import.meta.url), 'utf8');

    assert.match(html, /url=\/3dvr-world\//i);
    assert.match(html, /location\.replace\('\/3dvr-world\/'\)/);
    assert.match(html, /This route moved to 3DVR World/i);
  });
});
