import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

describe('3dvr-web customer journey copy', () => {
  it('keeps the homepage focused on concrete first steps and the portal start path', async () => {
    const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
    const heroHtml = html.match(/<section class="hero">[\s\S]*?<\/section>/)?.[0] || '';
    const heroIndex = html.indexOf('<section class="hero">');
    const planLaneIndex = html.indexOf('<section class="plan-lane-section"');
    const whatWeDoIndex = html.indexOf('<section id="vision"');

    assert.match(html, /Websites\. Apps\. Direct support\./);
    assert.match(html, /We help small businesses actually launch\./);
    assert.match(html, /Launch a site, offer, or simple business system with direct support from idea to live\./);
    assert.match(html, /Start Free/);
    assert.match(html, /Start a project/);
    assert.match(html, /Launch in 3 Days/);
    assert.match(html, /A clear place to land when you need a site, support, or a launch plan\./);
    assert.match(html, /data-portal-path="\/start\/"/);
    assert.match(html, /data-portal-path="\/free-trial\.html"/);
    assert.match(html, /data-portal-path="\/billing\/\?plan=starter"/);
    assert.match(html, /data-portal-path="\/billing\/\?plan=pro"/);
    assert.match(html, /data-portal-path="\/billing\/\?plan=builder"/);
    assert.match(html, /data-portal-path="\/billing\/\?plan=embedded"/);
    assert.doesNotMatch(html, /Plans after the offer is clear/);
    assert.match(html, /Pick the lane that fits\./);
    assert.match(html, /Get organized first/);
    assert.match(html, /Light monthly support/);
    assert.match(html, /Launch in 3 Days/);
    assert.match(html, /Default for businesses/);
    assert.match(html, /Run one calmer team system/);
    assert.match(html, /One-time payment or deposit/);
    assert.match(html, /\$5/);
    assert.match(html, /\$20/);
    assert.match(html, /\$50/);
    assert.match(html, /\$200/);
    assert.match(html, /Enterprise/);
    assert.match(html, /Custom/);
    assert.match(html, /What We Do/);
    assert.match(html, /Build your website or app/);
    assert.match(html, /Help you figure out the offer/);
    assert.match(html, /Stay with you as it grows/);
    assert.match(html, /Calendar Hub/);
    assert.match(html, /Open the calendar →/);
    assert.doesNotMatch(html, /Choose a lane, continue in portal/);
    assert.doesNotMatch(html, /Calendar front and center/);
    assert.doesNotMatch(html, /Use Life to log/);
    assert.doesNotMatch(html, /Join a Cell/);
    assert.doesNotMatch(html, /Life starter/);
    assert.match(html, /Simple ways to work together/);
    assert.doesNotMatch(html, /Plan fit guide/);
    assert.doesNotMatch(html, /Get structure first\./);
    assert.doesNotMatch(html, /Launch the first page or offer\./);
    assert.doesNotMatch(html, /Default for active businesses\.<\/span>/);
    assert.doesNotMatch(html, /Tap a card to continue in portal\./);
    assert.match(html, /Family &amp; Friends/);
    assert.match(html, /\$5 monthly/);
    assert.match(html, /Light monthly support for people close to the work who want to help keep 3dvr moving\./);
    assert.match(html, /For launching your product, brand, or first offer immediately\./);
    assert.match(html, /Choose Plan/);
    assert.doesNotMatch(html, /Start in Portal/);
    assert.doesNotMatch(html, /Continue in Portal/);
    assert.doesNotMatch(html, /when it needs to become real now/);
    assert.doesNotMatch(html, /Use this for Launch in 3 Days when the offer, site, or first page still needs to become real\./);
    assert.match(html, /Default for active businesses that need a site, follow-up, updates, and calmer operations\./);
    assert.match(html, /Pair it with a setup sprint when you want the first workflow built faster\./);
    assert.match(html, /Best for support teams, organizations, and shared workflows that need one calmer operating lane\./);
    assert.doesNotMatch(html, /\$20 starting point/);
    assert.doesNotMatch(html, /See the launch flow/);
    assert.match(html, /A clear place to land when you need a site, support, or a launch plan\./);
    assert.doesNotMatch(html, /Websites\. Apps\. Real support\./);
    assert.doesNotMatch(html, /A real place to land when you need a site, support, or a launch plan\./);
    assert.doesNotMatch(html, /Best for real businesses that need a site, follow-up, updates, and calmer operations\./);
    assert.match(html, /Trusted by friends, family, and small businesses/);
    assert.match(html, /See plans/);
    assert.match(html, /hero-logo-card/);
    assert.ok(heroIndex !== -1, 'Hero section should exist');
    assert.ok(planLaneIndex !== -1, 'Plan lane section should exist');
    assert.ok(whatWeDoIndex !== -1, 'What We Do section should exist');
    assert.ok(heroIndex < planLaneIndex, 'Plan lane should move below the hero');
    assert.ok(planLaneIndex < whatWeDoIndex, 'Plan lane should sit before What We Do');
    assert.doesNotMatch(heroHtml, /plan-lane-section/);
    assert.doesNotMatch(heroHtml, /Pick the lane that fits\./);
    assert.doesNotMatch(heroHtml, /data-growth-cta="plan-free"/);
    assert.doesNotMatch(heroHtml, /data-growth-feedback=/);
    assert.doesNotMatch(html, /Does this explain the offer clearly\?/);
    assert.doesNotMatch(html, /Still vague/);
    assert.doesNotMatch(html, /Start free in portal/);
    assert.doesNotMatch(html, /Not just plan\. Not just think about it\./);
    assert.doesNotMatch(html, /Open the full-screen 3DVR world prototype/);
    assert.match(html, /Nomad system direction/);
    assert.match(html, /Portable work, open hardware, and a calmer way to build on the move\./);
    assert.match(html, /Explore the nomad system/);
    assert.match(html, /Read the broader vision/);
    assert.match(html, /href="nomad-system\.html"/);
    assert.match(html, /What the stack includes/);
    assert.match(html, /Portal command center/);
    assert.match(html, /Start in the browser with one identity, one launcher, and one calmer operating lane\./);
    assert.match(html, /Portal layer/);
    assert.match(html, /OS direction/);
    assert.match(html, /Open portal\.3dvr\.tech/);
    assert.match(html, /href="system\.html"/);
    assert.match(html, /See full system map/);
    assert.doesNotMatch(html, /<section id="system"/);
    assert.doesNotMatch(html, /Message me/i);
    assert.doesNotMatch(html, /mailto:3dvr\.tech@gmail\.com\?subject=3DVR%20Project%20Inquiry/);
    assert.doesNotMatch(html, /Plan your week\. Get support\. Launch work\./);
  });

  it('moves the full Portal Browser OS system map onto its own page', async () => {
    const html = await readFile(new URL('../system.html', import.meta.url), 'utf8');
    assert.match(html, /One system\. Any device\./);
    assert.match(html, /Portal, Browser, OS/);
    assert.match(html, /Start in your browser\. Grow into your own operating system\./);
    assert.match(html, /The same 3dvr account,/);
    assert.match(html, /Linux-based/);
    assert.match(html, /control/);
    assert.match(html, /without starting over\./);
    assert.match(html, /Cloud workspace and identity/);
    assert.match(html, /Runtime, launcher, and media environment/);
    assert.match(html, /TommyOS direction for deeper control/);
    assert.match(html, /Open the portal command center/);
    assert.match(html, /href="pocket-workstation\.html"/);
    assert.match(html, /href="nomad-system\.html"/);
  });

  it('keeps the portfolio projects room visually connected to the world', async () => {
    const html = await readFile(new URL('../pages/portfolio.html', import.meta.url), 'utf8');
    assert.match(html, /Projects room/);
    assert.match(html, /behind the secret attic/);
    assert.match(html, /Back to the world/);
    assert.match(html, /Open portal/);
    assert.match(html, /project-intro/);
    assert.match(html, /A snapshot of recent launches, community experiments, and passion projects/);
  });

  it('makes the main plans page explicit about continuing in the portal', async () => {
    const html = await readFile(new URL('../subscribe/index.html', import.meta.url), 'utf8');
    assert.match(html, /Launch in 3 Days is the fast entry point\. Builder at \$50\/month is the default business lane/);
    assert.match(html, /Default for active businesses/);
    assert.match(html, /Get organized, sort out your next steps, and start using the portal without paying first\./);
    assert.match(html, /Choose by business type/);
    assert.match(html, /See professional-services fit/);
    assert.match(html, /See local-service fit/);
    assert.match(html, /See Enterprise fit/);
    assert.match(html, /Daily check-ins and weekly reflection/);
    assert.match(html, /What happens after you click/);
    assert.match(html, /Pick the right lane/);
    assert.match(html, /Keep one account/);
    assert.match(html, /Start the customer journey/);
    assert.match(html, /custom one-time payment/);
    assert.match(html, /Open portal start/);
    assert.match(html, /No credit card required\. Create one portal account and start organizing what matters\./);
    assert.match(html, /Start Free in Portal/);
    assert.match(html, /Continue to Portal for \$5/);
    assert.match(html, /Continue to Portal for \$20/);
    assert.match(html, /Continue to Portal for \$50/);
    assert.match(html, /Continue to Portal for Enterprise/);
    assert.match(html, /Open custom checkout in Portal/);
    assert.doesNotMatch(html, /Start free with Life/);
    assert.doesNotMatch(html, /Life starter/);
  });

  it('keeps the free plan detail page aligned with the portal onboarding flow', async () => {
    const html = await readFile(new URL('../subscribe/free-plan.html', import.meta.url), 'utf8');
    assert.match(html, /Get organized, sort out your next steps, and start inside the portal\./);
    assert.match(html, /The free plan gives you a simple place to check in daily, reflect each week, and build momentum before you pay for anything\./);
    assert.match(html, /Start Free/);
    assert.match(html, /Open start flow/);
    assert.match(html, /Open the portal start flow, choose your lane, and personalize the way you track and organize your day\./);
    assert.doesNotMatch(html, /open Life inside the portal/i);
    assert.doesNotMatch(html, /Life starter/);
  });

  it('keeps paid plan detail pages explicit about the portal billing handoff', async () => {
    const starterHtml = await readFile(new URL('../subscribe/family-friends.html', import.meta.url), 'utf8');
    const founderHtml = await readFile(new URL('../subscribe/founder-plan.html', import.meta.url), 'utf8');
    const builderHtml = await readFile(new URL('../subscribe/builder-plan.html', import.meta.url), 'utf8');
    assert.match(starterHtml, /Continue to Portal for \$5/);
    assert.match(founderHtml, /Continue to Portal for Founder/);
    assert.match(builderHtml, /Continue to Portal for Builder/);
  });

  it('ships segment pages for the three paid wedges', async () => {
    const professionalHtml = await readFile(new URL('../subscribe/professional-services.html', import.meta.url), 'utf8');
    const localHtml = await readFile(new URL('../subscribe/local-services.html', import.meta.url), 'utf8');
    const supportHtml = await readFile(new URL('../subscribe/support-teams.html', import.meta.url), 'utf8');

    assert.match(professionalHtml, /For Professional Services/);
    assert.match(professionalHtml, /Keep warm leads moving without building a giant sales stack\./);
    assert.match(professionalHtml, /Default business lane when you want more replies, steadier follow-up, and one place to run the week\./);
    assert.match(professionalHtml, /one-time setup sprint work/);
    assert.match(professionalHtml, /Continue to Portal for Builder/);
    assert.match(localHtml, /For Local Services/);
    assert.match(localHtml, /Stop letting calls, quotes, and follow-up slip through the cracks\./);
    assert.match(localHtml, /Default business lane when the work is real, the owner is busy, and the main problem is keeping the week organized\./);
    assert.match(localHtml, /scoped setup sprint help/);
    assert.match(localHtml, /Continue to Portal for Builder/);
    assert.match(supportHtml, /For Support Teams/);
    assert.match(supportHtml, /Give the team one calmer system for people, follow-up, and weekly action\./);
    assert.match(supportHtml, /Enterprise \$200 \/ month/);
    assert.match(supportHtml, /Continue to Portal for Enterprise/);
    assert.match(supportHtml, /choose Enterprise instead of Builder/i);
    assert.match(supportHtml, /plan=embedded/);
  });

  it('keeps the campaign page exposed for higher-intent buyers', async () => {
    const html = await readFile(new URL('../launch-your-site.html', import.meta.url), 'utf8');
    assert.match(html, /Launch your website, offer, or project without getting stuck in tech\./);
    assert.match(html, /Message me/);
    assert.match(html, /A simple offer people can understand and say yes to\./);
    assert.match(html, /Start with direct help, move into Builder when the business is active/);
    assert.match(html, /custom one-time payments only when the project actually needs a scoped deposit or checkout/);
    assert.match(html, /Show up clearly fast\./);
    assert.match(html, /reads cleanly on mobile and gives visitors a clear next step\./);
    assert.match(html, /Builder/);
    assert.match(html, /Custom/);
    assert.match(html, /One-time payment/);
    assert.match(html, /project checkout, deposit, or sprint instead of another monthly plan/);
    assert.match(html, /mailto:3dvr\.tech@gmail\.com\?subject=3DVR%20Project%20Inquiry/);
    assert.doesNotMatch(html, /Look credible fast\./);
    assert.doesNotMatch(html, /looks credible on mobile/);
    assert.doesNotMatch(html, /Talk through scope/);
    assert.doesNotMatch(html, /Why is there a \$5 plan/);
  });

  it('ships the Launch in 3 Days page as the direct founder offer', async () => {
    const html = await readFile(new URL('../launch-in-3-days.html', import.meta.url), 'utf8');
    assert.match(html, /<title>Launch in 3 Days \| 3dvr\.tech<\/title>/);
    assert.match(html, /Get the first real version live fast\./);
    assert.match(html, /This is not a long consulting process\./);
    assert.match(html, /The three questions that keep the build clean\./);
    assert.match(html, /What are you trying to build or improve right now\?/);
    assert.match(html, /What is stopping you from launching or growing it\?/);
    assert.match(html, /If this worked perfectly, what would it do for you\?/);
    assert.match(html, /I help people go from idea to live page in 3 days\./);
    assert.match(html, /What you are buying is not just a website\./);
    assert.match(html, /Continue to portal for Founder/);
    assert.match(html, /Need Builder instead\?/);
    assert.match(html, /Billing and account setup continue in portal\./);
    assert.match(html, /data-portal-path="\/billing\/\?plan=pro"/);
    assert.match(html, /data-portal-path="\/billing\/\?plan=builder"/);
    assert.match(html, /data-preserve-portal-origin href="subscribe\/index\.html"/);
    assert.match(html, /mailto:3dvr\.tech@gmail\.com\?subject=Launch%20in%203%20Days/);
    assert.match(html, /src="subscribe\/portal-links\.js"/);
    assert.doesNotMatch(html, /hello@3dvr\.tech/);
  });

  it('ships the nomad system page as a dedicated direction page', async () => {
    const html = await readFile(new URL('../nomad-system.html', import.meta.url), 'utf8');
    assert.match(html, /<title>3dvr\.tech Nomad System<\/title>/);
    assert.match(html, /Open-source tools for life on the move/);
    assert.match(html, /Live anywhere\./);
    assert.match(html, /Build anything\./);
    assert.match(html, /Open-source ecology for digital nomads/);
    assert.match(html, /The 3dvr nomad system/);
    assert.match(html, /What we're offering first/);
    assert.match(html, /Start with membership/);
    assert.match(html, /See membership options/);
    assert.match(html, /mailto:3dvr\.tech@gmail\.com\?subject=3dvr%20Nomad%20System/);
    assert.doesNotMatch(html, /tmsteph1290@gmail\.com/);
  });
});
