import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('homepage ships Gun-backed experiment and focused CTA plumbing', async () => {
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  const js = await readFile(new URL('../growth/homepage-experiment.js', import.meta.url), 'utf8');

  assert.match(html, /id="heroEyebrow"/);
  assert.match(html, /id="heroHeadlinePrimary"/);
  assert.match(html, /id="heroBody"/);
  assert.doesNotMatch(html, /id="heroHeadlineSecondary"/);
  assert.doesNotMatch(html, /id="heroFeedbackPrompt"/);
  assert.doesNotMatch(html, /id="heroFeedbackStatus"/);
  assert.doesNotMatch(html, /data-growth-feedback=/);
  assert.match(html, /data-growth-cta="sticky-start-free"/);
  assert.match(html, /data-growth-cta="start-project-primary"/);
  assert.match(html, /data-growth-cta="see-plans"/);
  assert.match(html, /class="hero-logo-card(?:\s|")/);
  assert.match(html, /Build the future/);
  assert.doesNotMatch(html, /Build the future\./);
  assert.doesNotMatch(html, /data-growth-cta="enter-3dvr-world"/);
  assert.match(html, /class="plan-lane-section"/);
  assert.match(html, /data-growth-cta="plan-free"/);
  assert.match(html, /data-growth-cta="plan-starter"/);
  assert.match(html, /grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(html, /@media \(min-width:\s*1500px\)\s*{\s*\.features-grid\s*{\s*grid-template-columns:\s*repeat\(5,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(html, /data-growth-cta="sticky-start-free"[^>]+data-portal-path="\/free-trial\.html"/);
  assert.match(html, /data-growth-cta="start-project-primary"[^>]+data-portal-path="\/start\/"/);
  assert.match(html, /data-growth-cta="plan-free"[^>]+data-portal-path="\/free-trial\.html"/);
  assert.match(html, /data-growth-cta="plan-starter"[^>]+data-portal-path="\/billing\/\?plan=starter"/);
  assert.match(html, /data-growth-cta="plan-20"[^>]+data-portal-path="\/billing\/\?plan=pro"/);
  assert.match(html, /data-growth-cta="plan-50"[^>]+data-portal-path="\/billing\/\?plan=builder"/);
  assert.match(html, /data-growth-cta="plan-200"[^>]+data-portal-path="\/billing\/\?plan=embedded"/);
  assert.match(html, /data-growth-cta="plan-custom"/);
  assert.doesNotMatch(html, /data-growth-cta="launch-in-3-days"/);
  assert.match(html, /href="nomad-system\.html"[^>]+data-growth-cta="explore-nomad-system"/);
  assert.match(html, /data-portal-path="\/billing\/\?plan=custom"/);
  assert.match(html, /href="https:\/\/portal\.3dvr\.tech\/billing\/\?plan=custom"/);
  assert.match(html, /src="subscribe\/portal-links\.js"/);
  assert.doesNotMatch(html, /data-growth-cta="sticky-start-free"[^>]+href="subscribe\/free-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="start-free-primary"[^>]+href="subscribe\/free-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-free"[^>]+href="subscribe\/free-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-starter"[^>]+href="subscribe\/family-friends\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-20"[^>]+href="subscribe\/founder-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-50"[^>]+href="subscribe\/builder-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-200"[^>]+href="subscribe\/support-teams\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-custom"[^>]+href="launch-your-site\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="message-me"/);
  assert.match(html, /src="https:\/\/cdn\.jsdelivr\.net\/npm\/gun\/gun\.js"/);
  assert.match(html, /src="growth\/homepage-experiment\.js"/);

  assert.match(js, /EXPERIMENT_CONFIG_PATH = \['3dvr-portal', 'growth', 'experiments', 'homepage-hero', 'config'\]/);
  assert.match(js, /EXPERIMENT_EVENT_PATH = \['3dvr-portal', 'growth', 'experiments', 'homepage-hero', 'events'\]/);
  assert.match(js, /eyebrow: 'Launch fast\. Start selling\.'/);
  assert.match(js, /primary: 'Get your project live\.'/);
  assert.match(js, /function chooseVariant/);
  assert.match(js, /function applyVariant/);
  assert.match(js, /function logView/);
  assert.match(js, /function logCtaClick/);
  assert.doesNotMatch(js, /FEEDBACK_EVENT_PATH/);
  assert.doesNotMatch(js, /function submitFeedback/);
});
