import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('homepage ships Gun-backed experiment and feedback plumbing', async () => {
  const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
  const js = await readFile(new URL('../growth/homepage-experiment.js', import.meta.url), 'utf8');

  assert.match(html, /id="heroEyebrow"/);
  assert.match(html, /id="heroHeadlinePrimary"/);
  assert.match(html, /id="heroHeadlineSecondary"/);
  assert.match(html, /id="heroBody"/);
  assert.match(html, /id="heroFeedbackPrompt"/);
  assert.match(html, /id="heroFeedbackStatus"/);
  assert.match(html, /data-growth-feedback="clear"/);
  assert.match(html, /data-growth-feedback="unclear"/);
  assert.match(html, /data-growth-cta="sticky-start-free"/);
  assert.match(html, /data-growth-cta="start-free-primary"/);
  assert.match(html, /data-growth-cta="see-plans"/);
  assert.match(html, /data-growth-cta="for-service-businesses"/);
  assert.match(html, /data-growth-cta="enter-3dvr-world"/);
  assert.match(html, /hero-enter-card/);
  assert.match(html, /Enter here/);
  assert.match(html, /Open the 3D world/);
  assert.match(html, /data-growth-cta="enter-3dvr-world"[^>]+hidden/);
  assert.match(html, /data-feature-flag="world"/);
  assert.match(html, /feature-flags\.js/);
  assert.match(html, /Touch \+ tilt ready/);
  assert.match(html, /data-growth-cta="plan-free"/);
  assert.match(html, /data-growth-cta="sticky-start-free"[^>]+data-portal-path="\/free-trial\.html"/);
  assert.match(html, /data-growth-cta="start-free-primary"[^>]+data-portal-path="\/free-trial\.html"/);
  assert.match(html, /data-growth-cta="plan-free"[^>]+data-portal-path="\/free-trial\.html"/);
  assert.match(html, /data-growth-cta="plan-20"[^>]+data-portal-path="\/billing\/\?plan=pro"/);
  assert.match(html, /data-growth-cta="plan-50"[^>]+data-portal-path="\/billing\/\?plan=builder"/);
  assert.match(html, /data-growth-cta="plan-200"[^>]+data-portal-path="\/billing\/\?plan=embedded"/);
  assert.match(html, /data-growth-cta="plan-custom"/);
  assert.match(html, /data-growth-cta="launch-in-3-days"/);
  assert.match(html, /href="launch-in-3-days\.html"[^>]+data-growth-cta="launch-in-3-days"/);
  assert.match(html, /href="3dvr-world\/"[^>]+data-growth-cta="enter-3dvr-world"[^>]+hidden/);
  assert.match(html, /href="nomad-system\.html"[^>]+data-growth-cta="explore-nomad-system"/);
  assert.match(html, /data-portal-path="\/billing\/\?plan=custom"/);
  assert.match(html, /href="https:\/\/portal\.3dvr\.tech\/billing\/\?plan=custom"/);
  assert.match(html, /src="subscribe\/portal-links\.js"/);
  assert.doesNotMatch(html, /data-growth-cta="sticky-start-free"[^>]+href="subscribe\/free-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="start-free-primary"[^>]+href="subscribe\/free-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-free"[^>]+href="subscribe\/free-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-20"[^>]+href="subscribe\/founder-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-50"[^>]+href="subscribe\/builder-plan\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-200"[^>]+href="subscribe\/support-teams\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="plan-custom"[^>]+href="launch-your-site\.html"/);
  assert.doesNotMatch(html, /data-growth-cta="message-me"/);
  assert.match(html, /data-growth-cta="segment-professional-services"/);
  assert.match(html, /src="https:\/\/cdn\.jsdelivr\.net\/npm\/gun\/gun\.js"/);
  assert.match(html, /src="growth\/homepage-experiment\.js"/);

  assert.match(js, /EXPERIMENT_CONFIG_PATH = \['3dvr-portal', 'growth', 'experiments', 'homepage-hero', 'config'\]/);
  assert.match(js, /EXPERIMENT_EVENT_PATH = \['3dvr-portal', 'growth', 'experiments', 'homepage-hero', 'events'\]/);
  assert.match(js, /FEEDBACK_EVENT_PATH = \['3dvr-portal', 'growth', 'feedback', 'homepage-hero'\]/);
  assert.match(js, /eyebrow: 'Launch fast\. Start selling\.'/);
  assert.match(js, /primary: 'Get your project live\.'/);
  assert.match(js, /secondary: 'Keep it moving with direct support\.'/);
  assert.match(js, /function chooseVariant/);
  assert.match(js, /function applyVariant/);
  assert.match(js, /function logView/);
  assert.match(js, /function logCtaClick/);
  assert.match(js, /function submitFeedback/);
});
