import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

describe('3dvr-web logo branding', () => {
  it('brands the SVG app logo as 3dvr.tech', async () => {
    const logo = await readFile(new URL('../assets/logo-3dvr.svg', import.meta.url), 'utf8');
    const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');

    assert.match(logo, /3dvr\.tech logo/);
    assert.match(logo, />3dvr</);
    assert.match(logo, />\.tech</);
    assert.match(html, /class="site-brand"[^>]+aria-label="3dvr\.tech home"/);
    assert.match(html, /<link rel="icon" type="image\/svg\+xml" href="\/favicon\.svg" \/>/);
    assert.match(html, /<img src="\/assets\/coin-mark\.svg" alt="">/);
    assert.match(html, /web-boot-coin-spin/);
    assert.match(html, /class="site-token-mark" aria-hidden="true"/);
    assert.match(html, /class="site-token-mark__main">3dvr<\/span>/);
    assert.doesNotMatch(html, /class="site-token-mark__suffix">\.tech<\/span>/);
    assert.match(html, /\.site-token-mark::before/);
    assert.match(html, /#fff0a8 0%, #e8c85d 24%, #b88920 62%, #73500f 100%/);
    assert.match(html, /\.site-token-mark::after/);
    assert.doesNotMatch(html, /radial-gradient\(circle at 32% 24%, #45ffe3/);
    assert.doesNotMatch(html, /repeating-linear-gradient\(\s+45deg,\s+rgba\(255, 255, 255, 0\.18\)/);
    assert.match(html, /<span class="site-brand__name">3dvr<span>\.tech<\/span><\/span>/);
    assert.match(html, /<strong>3dvr<span>\.tech<\/span><\/strong>/);
    assert.match(html, /data-3dvr-token/);
    assert.match(html, /data-3dvr-token-canvas/);
    assert.match(html, /Interactive 3dvr\.tech 3D token/);
    assert.match(html, /\.hero-logo-card > img/);
    assert.match(html, /\.hero-token\[data-token-ready="true"\] \.hero-token__fallback/);
    const tokenHoverRule = html.match(
      /\.hero-logo-card--token:hover,\s+\.hero-logo-card--token:focus-visible\s+\{(?<body>[\s\S]*?)\n\s+\}/
    )?.groups?.body ?? '';
    assert.match(tokenHoverRule, /translate3d\(0, 0, 0\)/);
    assert.doesNotMatch(tokenHoverRule, /scale\(/);
    assert.match(html, /homepage-logo-token\.js/);
    assert.match(html, /app-boot-enabled/);
    assert.match(html, /display-mode: standalone/);
    assert.match(html, /document\.referrer\.startsWith\('android-app:\/\/'\)/);
  });

  it('ships a touch and mouse driven Three.js token for the homepage logo', async () => {
    const token = await readFile(new URL('../homepage-logo-token.js', import.meta.url), 'utf8');

    assert.match(token, /THREE_CDN_URL/);
    assert.match(token, /three\.js\/r128\/three\.min\.js/);
    assert.match(token, /IDLE_QUARTER_SPIN_SPEED = \(Math\.PI \* 2\) \/ 18000/);
    assert.match(token, /IDLE_WOBBLE_X = 0\.025/);
    assert.match(token, /IDLE_WOBBLE_Z = 0\.012/);
    assert.match(token, /DRAG_SPIN_FACTOR = 0\.018/);
    assert.match(token, /DRAG_VERTICAL_SPIN_FACTOR = 0\.034/);
    assert.match(token, /MAX_SPIN_MOMENTUM = 0\.014/);
    assert.match(token, /MAX_VERTICAL_SPIN_MOMENTUM = 0\.032/);
    assert.match(token, /SPIN_MOMENTUM_DECAY = 0\.992/);
    assert.match(token, /VERTICAL_SPIN_MOMENTUM_DECAY = 0\.986/);
    assert.match(token, /ACTIVE_FRONT_FLIP_TARGET_RETURN = 0\.018/);
    assert.match(token, /FRONT_FLIP_SETTLE_VELOCITY = 0\.0012/);
    assert.match(token, /FULL_TURN = Math\.PI \* 2/);
    assert.match(token, /MANUAL_X_TARGET_RETURN = 0\.14/);
    assert.match(token, /MANUAL_X_CURRENT_RETURN = 0\.24/);
    assert.match(token, /MANUAL_TARGET_RETURN = 0\.1/);
    assert.match(token, /MANUAL_CURRENT_RETURN = 0\.18/);
    assert.match(token, /CylinderGeometry/);
    assert.match(token, /TorusGeometry/);
    assert.match(token, /CylinderGeometry\(1\.45, 1\.45, 0\.11/);
    assert.match(token, /ExtrudeGeometry/);
    assert.match(token, /depth: 0\.07/);
    assert.match(token, /bevelEnabled: true/);
    assert.match(token, /makeCoinLettering/);
    assert.match(token, /back\.rotation\.y = Math\.PI/);
    assert.match(token, /COIN_FONT_URL/);
    assert.match(token, /BoxGeometry\(0\.018, 0\.18, 0\.014\)/);
    assert.match(token, /for \(let index = 0; index < 96; index \+= 1\)/);
    assert.doesNotMatch(token, /fillText\('\.tech'/);
    assert.match(token, /fillText\('3dvr', 0, 0\)/);
    assert.match(token, /Approximate the raised face/);
    assert.doesNotMatch(token, /ring <= 5/);
    assert.match(token, /beadMaterial/);
    assert.match(token, /\[1\.18, 0\.98\]/);
    assert.doesNotMatch(token, /size \* 0\.32/);
    assert.match(token, /context\.lineTo\(outerX, outerY\)/);
    assert.doesNotMatch(token, /portalPhase|portalRings|MeshBasicMaterial|69f5ff|portalGradient/);
    assert.match(token, /CanvasTexture/);
    assert.match(token, /targetX: 0/);
    assert.match(token, /targetY: 0/);
    assert.match(token, /targetZ: 0/);
    assert.match(token, /idleSpin/);
    assert.match(token, /spinVelocityX/);
    assert.match(token, /spinVelocityY/);
    assert.match(token, /state\.idleSpin \+= elapsed \* \(IDLE_QUARTER_SPIN_SPEED \+ state\.spinVelocityY\)/);
    assert.match(token, /state\.targetX \+= elapsed \* state\.spinVelocityX/);
    assert.match(token, /nearestFullTurn/);
    assert.match(token, /settleFrontFlipAxis/);
    assert.match(token, /const verticalIntent = Math\.abs\(dy\) \/ Math\.max\(Math\.abs\(dx\), Math\.abs\(dy\), 1\)/);
    assert.match(token, /const verticalSpinDelta = dy \* DRAG_VERTICAL_SPIN_FACTOR \* verticalIntent/);
    assert.match(token, /state\.targetX \+= verticalSpinDelta/);
    assert.doesNotMatch(token, /idleSpin = .*% \(Math\.PI \* 2\)/);
    assert.match(token, /getRenderRotation/);
    assert.match(token, /pointerdown/);
    assert.match(token, /pointermove/);
    assert.match(token, /releasePointerCapture/);
    assert.match(token, /const xTargetReturn =/);
    assert.match(token, /state\.targetX \+= \(state\.restX - state\.targetX\) \* xTargetReturn/);
    assert.match(token, /__3dvrLogoToken/);
  });
});
